const orderList = [
  {
    id: "9",
    amount: "￥600.00",
    orderTitle: "南京机场接机",
    customerName: "耿先生",
    customerPhone: "1391****422",
    customerPhotos: "ho_info_01.jpeg",
    drivingTime: "2021.5.27",
    carType: "53座",
    scheduling: "南京禄口机场-世纪缘大酒店",
    carPhotos: ["ho-order-09-01.png", "ho-order-09-02.png"],
    hasPapers: "乘客险",
    priceInclude: "司机工作餐/油费/路桥费/停车费/车辆费使用费/司机服务费",
    priceExclude: "一价全包，无自费项目",
    serviceFleet: "帛华汽车服务有限公司",
    mainPicture: "ho-order-09-01.png",
    index: 1,
  },
  {
    id: "10",
    amount: "￥760.00",
    orderTitle: "南京市内一日游",
    customerName: "薛丹丹",
    customerPhone: "1391****572",
    customerPhotos: "ho_info_01.jpeg",
    drivingTime: "2021.6.3",
    carType: "33座",
    scheduling: "南京市锁金村—栖霞欢乐谷",
    carPhotos: ["ho-order-10-01.png", "ho-order-10-02.png"],
    hasPapers: "乘客险",
    priceInclude: "司机工作餐/油费/路桥费/停车费/车辆费使用费/司机服务费",
    priceExclude: "一价全包，无自费项目",
    serviceFleet: "帛华汽车服务有限公司",
    mainPicture: "ho-order-10-main.png",
    index: 2,
  },
  {
    id: "1",
    amount: "￥2400.00",
    orderTitle: "溧阳三日游",
    customerName: "刘女士",
    customerPhone: "1378****472",
    customerPhotos: "ho_info_01.jpeg",
    drivingTime: "2020.3.12-2020.3.14",
    carType: "14座丰田海狮",
    scheduling: "南京市中医院—溧阳天目湖—南山竹海",
    carPhotos: ["ho-order-01-01.png", "ho-order-01-02.png"],
    hasPapers: "乘客险",
    priceInclude: "司机工作餐/油费/路桥费/停车费/车辆费使用费/司机服务费",
    priceExclude: "一价全包，无自费项目",
    serviceFleet: "帛华汽车服务有限公司",
    mainPicture: "ho-order-01-main.png",
    index: 3,
  },
  {
    id: "2",
    amount: "￥2600.00",
    orderTitle: "南京-苏州-无锡两日游",
    customerName: "张先生",
    customerPhone: "1515****468",
    customerPhotos: "ho_info_02.jpeg",
    drivingTime: "2020.4.18-2020.4.19",
    carType: "7座别克商务",
    scheduling: "南京市江宁万达—苏州拙政园--无锡拈花湾",
    carPhotos: ["ho-order-02-01.png", "ho-order-02-02.png"],
    hasPapers: "乘客险",
    priceInclude: "司机工作餐/油费/路桥费/停车费/车辆费使用费/司机服务费",
    priceExclude: "一价全包，无自费项目",
    serviceFleet: "帛华汽车服务有限公司",
    mainPicture: "ho-order-02-main.png",
    index: 4,
  },
  {
    id: "3",
    amount: "￥6800.00",
    orderTitle: "乌镇景区-普陀山三日游",
    customerName: "王先生",
    customerPhone: "1732****898",
    customerPhotos: "ho_info_03.jpeg",
    drivingTime: "2020.5.1-2020.5.3",
    carType: "53座大巴",
    scheduling: "无锡硕放机场—乌镇风景区--普陀山",
    carPhotos: ["ho-order-03-01.png", "ho-order-03-02.png"],
    hasPapers: "乘客险",
    priceInclude: "司机工作餐/油费/路桥费/停车费/车辆费使用费/司机服务费",
    priceExclude: "一价全包，无自费项目",
    serviceFleet: "帛华汽车服务有限公司",
    mainPicture: "ho-order-03-main.png",
    index: 5,
  },
  {
    id: "4",
    amount: "￥1000.00",
    orderTitle: "苏州郊外一日游（西山风景区）",
    customerName: "王虎",
    customerPhone: "1391****602",
    customerPhotos: "ho_info_04.jpeg",
    drivingTime: "2020.6.18",
    carType: "37座",
    scheduling: "苏州市内包车团建（苏州晶汇大厦—西山）",
    carPhotos: ["ho-order-04-01.png", "ho-order-04-02.png"],
    hasPapers: "乘客险",
    priceInclude: "司机工作餐/油费/路桥费/停车费/车辆费使用费/司机服务费",
    priceExclude: "一价全包，无自费项目",
    serviceFleet: "帛华汽车服务有限公司",
    mainPicture: "ho-order-04-main.png",
    index: 6,
  },
  {
    id: "5",
    amount: "￥7800.00",
    orderTitle: "江苏浙江五日政府单位考察",
    customerName: "陈磊",
    customerPhone: "1762****648",
    customerPhotos: "ho_info_05.jpeg",
    drivingTime: "2021.3.28-2021.4.3",
    carType: "18座丰田考斯特",
    scheduling: "常州金坛-长兴县—湖州—杭州—萧山机场-常州",
    carPhotos: ["ho-order-05-01.png", "ho-order-05-02.png"],
    hasPapers: "乘客险",
    priceInclude: "司机工作餐/油费/路桥费/停车费/车辆费使用费/司机服务费",
    priceExclude: "一价全包，无自费项目",
    serviceFleet: "帛华汽车服务有限公司",
    mainPicture: "ho-order-05-main.png",
    index: 7,
  },
  // {
  //   id: "6",
  //   amount: "￥1500.00",
  //   orderTitle: "溧水一日游往返",
  //   customerName: "郭长章",
  //   customerPhone: "1589****522",
  //   customerPhotos: "ho_info_06.jpeg",
  //   drivingTime: "2021.4.22",
  //   carType: "53座大巴",
  //   scheduling: "南京新街口—溧水天生桥—傅家边—新街口",
  //   carPhotos: ["ho-order-06-01.png", "ho-order-06-02.png"],
  //   hasPapers: "乘客险",
  //   priceInclude: "司机工作餐/油费/路桥费/停车费/车辆费使用费/司机服务费",
  //   priceExclude: "一价全包，无自费项目",
  //   serviceFleet: "帛华汽车服务有限公司",
  //   mainPicture: "ho-order-06-main.png",
  //   index: 8,
  // },
  // {
  //   id: "7",
  //   amount: "￥3500.00",
  //   orderTitle: "九华山两日游",
  //   customerName: "范英宝",
  //   customerPhone: "1371****194",
  //   customerPhotos: "ho_info_07.jpeg",
  //   drivingTime: "2021.3.18—2021.3.19",
  //   carType: "45座",
  //   scheduling: "南京龙江—九华山风景区",
  //   carPhotos: [
  //     "ho-order-07-01.png",
  //     "ho-order-07-02.png",
  //   ],
  //   hasPapers: "乘客险",
  //   priceInclude: "司机工作餐/油费/路桥费/停车费/车辆费使用费/司机服务费",
  //   priceExclude: "一价全包，无自费项目",
  //   serviceFleet: "帛华汽车服务有限公司",
  //   mainPicture: "ho-order-07-main.png",
  //   index: 9,
  // },
  // {
  //   id: "8",
  //   amount: "￥7000.00",
  //   orderTitle: "黄山风景区四日游",
  //   customerName: "孙晨",
  //   customerPhone: "1515****604",
  //   customerPhotos: "ho_info_08.jpeg",
  //   drivingTime: "2021.5.20—2021.5.23",
  //   carType: "53座",
  //   scheduling: "南京龙江—歙县—宏村-黄山风景区",
  //   carPhotos: ["ho-order-08-01.png", "ho-order-08-02.png"],
  //   hasPapers: "乘客险",
  //   priceInclude: "司机工作餐/油费/路桥费/停车费/车辆费使用费/司机服务费",
  //   priceExclude: "一价全包，无自费项目",
  //   serviceFleet: "帛华汽车服务有限公司",
  //   mainPicture: "ho-order-08-main.png",
  //   index: 10,
  // },
];

const carTypeList = [
  {
    id: "8",
    carTitle: "7座别克商务(可坐乘客6人)",
    licensingTime: "2021/01/02",
    dealNums: "255",
    mainPicture: "ho_car_7.png",
  },
  {
    id: "5",
    carTitle: "17座江铃全顺(可坐乘客16人)",
    licensingTime: "2022/02/16",
    dealNums: "188",
    mainPicture: "ho_car_17.png",
  },
  {
    id: "10",
    carTitle: "17座依维柯牌(可坐乘客16人)",
    licensingTime: "2020/12/28",
    dealNums: "145",
    mainPicture: "ho_car_17_2.png",
  },
  {
    id: "6",
    carTitle: "19座金旅考斯特(可坐乘客18人)",
    licensingTime: "2022/05/25",
    dealNums: "120",
    mainPicture: "ho_car_19.png",
  },
  {
    id: "11",
    carTitle: "20座柯斯达牌(可坐乘客19人)",
    licensingTime: "2021/08/15",
    dealNums: "165",
    mainPicture: "ho_car_20.png",
  },
  {
    id: "7",
    carTitle: "20座柯斯达(可坐乘客19人)",
    licensingTime: "2020/11/03",
    dealNums: "198",
    mainPicture: "ho_car_20.png",
  },
  {
    id: "4",
    carTitle: "46座宇通大客车(可坐乘客45人)",
    licensingTime: "2021/04/12",
    dealNums: "146",
    mainPicture: "ho_car_46.png",
  },
  {
    id: "3",
    carTitle: "48座宇通大客车(可坐乘客47人)",
    licensingTime: "2022/04/12",
    dealNums: "233",
    mainPicture: "ho_car_48.png",
  },
  {
    id: "9",
    carTitle: "49座金旅牌(可坐乘客48人)",
    licensingTime: "2020/04/02",
    dealNums: "112",
    mainPicture: "ho_car_49.png",
  },
  {
    id: "1",
    carTitle: "54座金龙大客车(可坐乘客53人)",
    licensingTime: "2019/12/15",
    dealNums: "281",
    mainPicture: "ho_car_54.png",
  },
  {
    id: "12",
    carTitle: "54座青年牌(可坐乘客53人)",
    licensingTime: "2020/01/15",
    dealNums: "201",
    mainPicture: "ho_car_54_2.png",
  },
  {
    id: "2",
    carTitle: "55座海格大客车(可坐乘客54人)",
    licensingTime: "2021/07/24",
    dealNums: "331",
    mainPicture: "ho_car_55.png",
  },
];

const ho_orderList = [
  [
    {
      id: "01",
      amount: "￥2400.00",
      orderTitle: "【南京包车】南京14座大巴到南山竹海一天往返",
      customerName: "刘女士",
      customerPhone: "1378****472",
      customerPhotos: "@/assets/images/order/ho_info_01.jpeg",
      drivingTime: "2020.3.12-2020.3.14",
      carType: "14座丰田海狮",
      scheduling: "南京市中医院—溧阳天目湖—南山竹海",
      carPhotos: [
        "@/assets/images/order/ho-order-01-01.png",
        "@/assets/images/order/ho-order-01-02.png",
      ],
      hasPapers: "乘客险",
      priceInclude: "司机工作餐/油费/路桥费/停车费/车辆费使用费/司机服务费",
      priceExclude: "一价全包，无自费项目",
      serviceFleet: "帛华汽车服务有限公司",
      mainPicture: "ho-order-01-main.png",
    },
    {
      id: "02",
      amount: "￥2600.00",
      orderTitle: "【南京包车】南京14座大巴到南山竹海一天往返",
      customerName: "张先生",
      customerPhone: "1515****468",
      customerPhotos: "@/assets/images/order/ho_info_02.jpeg",
      drivingTime: "2020.4.18-2020.4.19",
      carType: "7座别克商务",
      scheduling: "南京市江宁万达—苏州拙政园--无锡拈花湾",
      carPhotos: [
        "@/assets/images/order/ho-order-02-01.png",
        "@/assets/images/order/ho-order-02-02.png",
      ],
      hasPapers: "乘客险",
      priceInclude: "司机工作餐/油费/路桥费/停车费/车辆费使用费/司机服务费",
      priceExclude: "一价全包，无自费项目",
      serviceFleet: "帛华汽车服务有限公司",
      mainPicture: "ho-order-02-main.png",
    },
    {
      id: "03",
      amount: "￥6800.00",
      orderTitle: "【南京包车】南京14座大巴到南山竹海一天往返",
      customerName: "王先生",
      customerPhone: "1732****898",
      customerPhotos: "@/assets/images/order/ho_info_03.jpeg",
      drivingTime: "2020.5.1-2020.5.3",
      carType: "53座大巴",
      scheduling: "无锡硕放机场—乌镇风景区--普陀山",
      carPhotos: [
        "@/assets/images/order/ho-order-03-01.png",
        "@/assets/images/order/ho-order-03-02.png",
      ],
      hasPapers: "乘客险",
      priceInclude: "司机工作餐/油费/路桥费/停车费/车辆费使用费/司机服务费",
      priceExclude: "一价全包，无自费项目",
      serviceFleet: "帛华汽车服务有限公司",
      mainPicture: "ho-order-03-main.png",
    },
    {
      id: "04",
      amount: "￥1000.00",
      orderTitle: "【南京包车】南京14座大巴到南山竹海一天往返",
      customerName: "王虎",
      customerPhone: "1391****602",
      customerPhotos: "@/assets/images/order/ho_info_04.jpeg",
      drivingTime: "2020.6.18",
      carType: "37座",
      scheduling: "苏州市内包车团建（苏州晶汇大厦—西山）",
      carPhotos: [
        "@/assets/images/order/ho-order-04-01.png",
        "@/assets/images/order/ho-order-04-02.png",
      ],
      hasPapers: "乘客险",
      priceInclude: "司机工作餐/油费/路桥费/停车费/车辆费使用费/司机服务费",
      priceExclude: "一价全包，无自费项目",
      serviceFleet: "帛华汽车服务有限公司",
      mainPicture: "ho-order-04-main.png",
    },
  ],
  [
    {
      id: "05",
      amount: "￥7800.00",
      orderTitle: "【南京包车】南京14座大巴到南山竹海一天往返",
      customerName: "陈磊",
      customerPhone: "1762****648",
      customerPhotos: "@/assets/images/order/ho_info_05.jpeg",
      drivingTime: "2021.3.28-2021.4.3",
      carType: "18座丰田考斯特",
      scheduling: "南京市中医院—溧阳天目湖—南山竹海",
      carPhotos: [
        "@/assets/images/order/ho-order-05-01.png",
        "@/assets/images/order/ho-order-05-02.png",
      ],
      hasPapers: "乘客险",
      priceInclude: "司机工作餐/油费/路桥费/停车费/车辆费使用费/司机服务费",
      priceExclude: "一价全包，无自费项目",
      serviceFleet: "帛华汽车服务有限公司",
      mainPicture: "ho-order-05-main.png",
    },
    {
      id: "06",
      amount: "￥1500.00",
      orderTitle: "【南京包车】南京14座大巴到南山竹海一天往返",
      customerName: "刘女士",
      customerPhone: "1589****522",
      customerPhotos: "@/assets/images/order/ho_info_06.jpeg",
      drivingTime: "2021.4.22",
      carType: "53座大巴",
      scheduling: "南京新街口—溧水天生桥—傅家边—新街口",
      carPhotos: [
        "@/assets/images/order/ho-order-06-01.png",
        "@/assets/images/order/ho-order-06-02.png",
      ],
      hasPapers: "乘客险",
      priceInclude: "司机工作餐/油费/路桥费/停车费/车辆费使用费/司机服务费",
      priceExclude: "一价全包，无自费项目",
      serviceFleet: "帛华汽车服务有限公司",
      mainPicture: "ho-order-06-main.png",
    },
    {
      id: "07",
      amount: "￥3500.00",
      orderTitle: "【南京包车】南京14座大巴到南山竹海一天往返",
      customerName: "范英宝",
      customerPhone: "1371****194",
      customerPhotos: "@/assets/images/order/ho_info_07.jpeg",
      drivingTime: "2021.3.18—2021.3.19",
      carType: "45座",
      scheduling: "南京龙江—九华山风景区",
      carPhotos: [
        "@/assets/images/order/ho-order-07-01.png",
        "@/assets/images/order/ho-order-07-02.png",
      ],
      hasPapers: "乘客险",
      priceInclude: "司机工作餐/油费/路桥费/停车费/车辆费使用费/司机服务费",
      priceExclude: "一价全包，无自费项目",
      serviceFleet: "帛华汽车服务有限公司",
      mainPicture: "ho-order-07-main.png",
    },
    {
      id: "08",
      amount: "￥7000.00",
      orderTitle: "【南京包车】南京14座大巴到南山竹海一天往返",
      customerName: "孙晨",
      customerPhone: "1515****604",
      customerPhotos: "@/assets/images/order/ho_info_08.jpeg",
      drivingTime: "2021.5.20—2021.5.23",
      carType: "14座丰田海狮",
      scheduling: "南京龙江—歙县—宏村-黄山风景区",
      carPhotos: [
        "@/assets/images/order/ho-order-08-01.png",
        "@/assets/images/order/ho-order-08-02.png",
      ],
      hasPapers: "乘客险",
      priceInclude: "司机工作餐/油费/路桥费/停车费/车辆费使用费/司机服务费",
      priceExclude: "一价全包，无自费项目",
      serviceFleet: "帛华汽车服务有限公司",
      mainPicture: "ho-order-08-main.png",
    },
  ],
];

export { orderList, carTypeList, ho_orderList };
